name: qr_code_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: 2.0.9
  url_launcher: ^6.2.6
  zoom_tap_animation: ^1.1.0
  pretty_qr_code: ^3.3.0
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  open_filex: ^4.4.0
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  gallery_saver: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/icons/


